name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - "*"

jobs:
  test-platforms:
    name: ${{ matrix.os.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            runs-on: windows-latest
            tox: windows
          - name: Linux
            runs-on: ubuntu-latest
            tox: linux
          - name: macOS
            runs-on: macos-latest
            tox: macos
        python:
          - name: CPython 3.6
            tox: py36
            action: 3.6
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python.name }}
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python.action }}.0-alpha - ${{ matrix.python.action }}.X'
          architecture: x64
      - uses: twisted/python-info-action@v1.0.1
      - name: Install Linux Qt6 dependencies
        if: matrix.os.name == 'Linux'
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes libgl1
          # Required to stubtest QtMultimedia
          sudo apt-get install --yes libpulse-mainloop-glib0
      - name: Install
        run: |
          pip install --upgrade pip setuptools wheel
          pip install tox
      - name: Test
        run: |
          tox -v -e ${{ matrix.python.tox }}-${{ matrix.os.tox }}

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test-platforms
    steps:
      - name: This
        shell: python
        run: |
          import this
